### ISSUE TITLE
where is docker-images ?

### ISSUE THREAD

**Issue by Alex-wwei** [Bujupah/yet-another-renderer#17]
bujupah/yet-another-renderer:lates is not found .

And I will rebuild the image, it occured the err: pull node:alpine3.19 timeout.

**Comment by Bujupah** [comment]
Hi @Alex-wwei,

Thanks for raising this 😀
I somehow forgot to update and push the docker image from my local to docker registry...

I will do this by end of day.

**Comment by Bujupah** [comment]
Docker registry update.
